# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ca958ce3663b8d53c5a97da71d01cdd6"
name = "my collection od"
application_url = "https://my-collection-od.vercel.app"
embedded = true

[access_scopes]
scopes = "write_app_proxy"

[auth]
redirect_urls = [
  "https://my-collection-od.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://my-collection-od.vercel.app"
subpath = "my-collection"
prefix = "apps"
